const bannerData = [
  {
    id: 1,
    title: "Chiếc bật lửa và váy công chúa",
    shortDescription: "Tình yêu lập trình viên thiên tài và nàng công chúa",
    fullDescription: `Phim Chiếc Bật Lửa Và Váy Công Chúa xoay quanh câu chuyện về nhân vật Chu Vận và Lý Tuân...`,
    bgImage: "/assets/lgtandprs-bg.png",
    posterImage: "/assets/lighter-and-princess.png",
    year: "2023",
    rating: 9.8,
    duration: "45 phút/tập",
    episodes: "36 tập",
    videoUrl: "https://www.youtube.com/embed/SkLVK4B5rqs?autoplay=1",
    genre: "TV Show",
    cast: ["Trần Phi Vũ", "Trương Tịnh Nghi"],
    tags: ["Tình cảm", "Thanh xuân", "Lập trình"],
  },
  {
    id: 2,
    title: "Khó dỗ dành",
    shortDescription: "Tình yêu giữa một cô gái và một chàng trai",
    fullDescription: `Khó Dỗ Dành – The First Frost kể về một chuyện tình đầy trắc trở của đôi bạn trẻ Ôn Dĩ Phàm và Tang Diên khi họ phải yêu đi yêu lại .`,
    bgImage: "/assets/khododanh-bg.png",
    posterImage: "/assets/khododanh.png",
    year: "2025",
    rating: 9.2,
    duration: "45 phút/tập",
    episodes: "32 tập",
    videoUrl: "https://www.youtube.com/embed/sT-wpjhYy-0?autoplay=1",
    genre: "Movie",
    cast: ["Bạch Kính Đình", "Chương Nhược Nam"],
    tags: ["Ngôn tình", "Hiện đại"],
  },

  {
    id: 3,
    title: "Bí mật nơi góc tối",
    shortDescription: "Thanh xuân Tình yêu Lập trình Chờ đợi",
    fullDescription: `Phim Bí Mật Nơi Góc Tối xoay quanh câu chuyện về nhân vật...`,
    bgImage: "/assets/bimatnoigoctoi-bg.png",
    posterImage: "/assets/bimatnoigoctoi.png",
    year: "2022",
    rating: 8.5,
    duration: "45 phút/tập",
    episodes: "30 tập",
    videoUrl: "https://www.youtube.com/embed/J_M18twFLeI?si=vLfBOc0pG1Vkjju3",
    genre: "TV Show",
    cast: ["Trần Triết Viễn", "Từ Mộng Khiết"],
    tags: ["Tình cảm", "Thanh Xuân"],
  },

  {
    id: 4,
    title: "Vụng trộm không thể giấu",
    shortDescription: "Thanh xuân Tình yêu Lập trình Bạn Thân",
    fullDescription: `Phim Vụng Trộm Không Thể Giấu xoay quanh câu chuyện về nhân vật...`,
    bgImage: "/assets/vtktg-bg.png",
    posterImage: "/assets/vtktg.png",
    year: "2023",
    rating: 9.5,
    duration: "45 phút/tập",
    episodes: "33 tập",
    videoUrl: "https://www.youtube.com/embed/eF57VHqjdys?si=Pbtnmjl29quSGmbE",
    genre: "TV Show",
    cast: ["Trần Triết Viễn", "Triệu Lộ Tư"],
    tags: ["Tình cảm", "Thanh Xuân", "Hài hước"],
  },
];

export default bannerData;
